name: Build VM Disk Image

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
        fail-fast: false
        matrix:
          version:
            - '9.2'
            - '9.3'
            - '9.4'
            - '10.0'

          architecture:
            - arm64
            - x86-64

          exclude:
            - version: 9.2
              architecture: arm64

            - version: 9.3
              architecture: arm64

            - version: 9.4
              architecture: arm64

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qemu-system-arm qemu-system-x86 qemu-utils

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: hashicorp/setup-packer@main
        with:
          version: "1.10.3"

      # - uses: mxschmitt/action-tmate@v3

      - name: Build Image
        run: |
          CHECKPOINT_DISABLE=1 PACKER_LOG=1 ./build.sh \
            '${{ matrix.version }}' \
            '${{ matrix.architecture }}' \
            -var headless=true

      - name: Extract Version
        id: version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          name: NetBSD ${{ steps.version.outputs.VERSION }}
          draft: true
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
